# From existing pytorch images on gcr
# Image: gcr.io/deeplearning-platform-release/pytorch-cpu.1-4
ARG BASE_IMAGE=gcr.io/deeplearning-platform-release/pytorch-cpu.1-4

FROM $BASE_IMAGE

# Install dependencies
RUN 

