name: Release Performance Testing

on:
  push:
    branches: [ master ]

env:
  GKE_LOCATION: us-central1

jobs:
  pytorch-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '316.0.0'
          service_account_key: ${{ secrets.GKE_SA_KEY_BASE64 }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
        shell: bash

      - name: Build and Push Docker Image
        run: |
          cd ci_pytorch
          docker build --tag "$IMAGE:$GITHUB_RUN_ID" -f
          docker push "$IMAGE:$GITHUB_RUN_ID"
        shell: bash

      - name: Install jsonnet
        run: |-
          go get github.com/google/go-jsonnet/cmd/jsonnet
        shell: bash

      - name: Get cluster credentials
        run: |-
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --region "$GKE_LOCATION"

      - name: Deploy the job on GKE
        run: |-
